// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqyUD1yMSKahCSLI1Ki-p1Nw7qpAEnzsw',
    appId: '1:321066244508:web:ca6106e71d00d53578d059',
    messagingSenderId: '321066244508',
    projectId: 'medicaltestapp-90651',
    authDomain: 'medicaltestapp-90651.firebaseapp.com',
    storageBucket: 'medicaltestapp-90651.appspot.com',
    measurementId: 'G-EE4KDDG2L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwzK2t4iDP0spYufWKraB_VeEym3wXROg',
    appId: '1:321066244508:android:7b8f63cb495545c378d059',
    messagingSenderId: '321066244508',
    projectId: 'medicaltestapp-90651',
    storageBucket: 'medicaltestapp-90651.appspot.com',
  );
}
